config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root "dashboards#index"
    resources :subjects, except: [:show]
    resources :users, except: [:show]
    resources :courses, except: [:edit, :update]
    resources :activities, only: [:index, :destroy]
  end

  namespace :supervisor do
    resources :courses, except: [:new, :create] do
      resource :assign_subjects, only: [:edit, :update]
      resource :assign_trainees, only: [:edit, :update]
      resource :assign_supervisors, only: [:edit, :update]
      resources :subjects, only: [:edit, :update]
    end
  end

  devise_for :users, path: "", path_names: {
    sign_in: "login",
    sign_out: "logout"
  }

  resources :users, only: [:show, :edit, :update]
  resources :courses, only: :show do
    resources :subjects, only: [:show, :update]
  end
  
  root "static_pages#home"
  get "help" => "static_pages#help"
  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/views/static_pages/about.html.erb
<% provide :title, t("views.pages.about_us") %>
<h1>
  <strong><%= t "views.pages.about_us" %></strong>
</h1>

app/views/static_pages/contact.html.erb
<% provide :title, t("views.pages.contact") %>
<h1>
  <strong><%= t "views.pages.contact" %></strong>
</h1>

app/views/static_pages/help.html.erb
<% provide :title, t("views.pages.help") %>
<h1>
  <strong><%= t "views.pages.help" %></strong>
</h1>

app/views/static_pages/home.html.erb
<% provide :title, t("views.pages.home") %>

<div class="container">
  <h2 class="text-center text-success">
    <b><%= t "views.messages.hello_name", name: current_user.name %></b>
  </h2>
  <div class="col-md-5">
    <% if current_user.managing_courses.any? %>
      <h3 class="text-danger">
        <%= t "views.messages.managing_courses" %>
      </h3>
      <table class="table">
        <% current_user.managing_courses.each_with_index do |managing_course, index| %>
          <tr>
            <td>
              <%= index + 1 %>. <%= link_to managing_course.name, managing_course %>
            </td>
          </tr>
        <% end %>
      </table>
      <%= link_to t("views.actions.manage"), supervisor_courses_path %>
    <% else %>
      <h3><%= t "views.messages.not_supervisor" %></h3>
    <% end %>

    <% if current_user.courses.any? %>
      <h3><%= t "views.messages.studying_courses" %></h3>
      <table class="table">
        <% current_user.courses.each_with_index do |course, index| %>
          <tr>
            <td>
              <%= index + 1 %>. <%= link_to course.name, course %>
            </td>
          </tr>
        <% end %>
      </table>
    <% else %>
      <h3><%= t "views.messages.not_trainee" %></h3>
    <% end %>
  </div>
</div>