config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root "dashboards#index"
    resources :subjects, except: [:show]
    resources :users, except: [:show]
    resources :courses, except: [:edit, :update]
    resources :activities, only: [:index, :destroy]
  end

  namespace :supervisor do
    resources :courses, except: [:new, :create] do
      resource :assign_subjects, only: [:edit, :update]
      resource :assign_trainees, only: [:edit, :update]
      resource :assign_supervisors, only: [:edit, :update]
      resources :subjects, only: [:edit, :update]
    end
  end

  devise_for :users, path: "", path_names: {
    sign_in: "login",
    sign_out: "logout"
  }

  resources :users, only: [:show, :edit, :update]
  resources :courses, only: :show do
    resources :subjects, only: [:show, :update]
  end
  
  root "static_pages#home"
  get "help" => "static_pages#help"
  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"

end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < ApplicationController
  before_action :admin_user!
  
  def index
    @users_count = User.count
    @courses_count = Course.count
    @subjects_counts = Subject.count
  end
end

app/views/admin/dashboards/index.html.erb
<% provide :title, t("views.pages.dashboard") %>

<h1 class="text-info"><%= t "views.messages.welcome_admin" %></h1>
<hr>
<div class="row">
  <div class="col-md-4">
    <%= link_to @users_count, admin_users_path, class: "glyphicon glyphicon-user object-icon" %>
  </div>
  <div class="col-md-4">
    <a href="#">
      <span class="glyphicon glyphicon-list-alt object-icon"><%= @courses_count %></span>
    </a>
  </div>
  <div class="col-md-4">
    <a href="">
      <span class="glyphicon glyphicon-file object-icon"><%= @subjects_counts %></span>
    </a>
  </div>
</div>