config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root "dashboards#index"
    resources :subjects, except: [:show]
    resources :users, except: [:show]
    resources :courses, except: [:edit, :update]
    resources :activities, only: [:index, :destroy]
  end

  namespace :supervisor do
    resources :courses, except: [:new, :create] do
      resource :assign_subjects, only: [:edit, :update]
      resource :assign_trainees, only: [:edit, :update]
      resource :assign_supervisors, only: [:edit, :update]
      resources :subjects, only: [:edit, :update]
    end
  end

  devise_for :users, path: "", path_names: {
    sign_in: "login",
    sign_out: "logout"
  }

  resources :users, only: [:show, :edit, :update]
  resources :courses, only: :show do
    resources :subjects, only: [:show, :update]
  end
  
  root "static_pages#home"
  get "help" => "static_pages#help"
  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"

end

app/models/user.rb
class User < ActiveRecord::Base
  include Logs

  devise :database_authenticatable, :rememberable, :trackable, :validatable
  has_many :user_courses, dependent: :destroy
  has_many :supervisor_courses, dependent: :destroy
  has_many :user_subjects, dependent: :destroy
  has_many :user_tasks, through: :user_subjects, dependent: :destroy
  has_many :activities, dependent: :destroy
  has_many :subjects, through: :user_subjects
  has_many :tasks, through: :user_tasks
  has_many :courses, through: :user_courses
  has_many :managing_courses, through: :supervisor_courses
  scope :recent, ->{order created_at: :desc}
  scope :supervisors, ->{where("id in (SELECT user_id FROM supervisor_courses)")}

  def self.send_trainees_report
    User.supervisors.each do |supervisor|
      ReportAtEndOfDays.perform_async supervisor.id
    end
  end

  def classmate? user
    course = self.courses.active_course.first
    course.users.include? user unless course.nil?
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :admin_user!
  before_action :init_user, only: [:edit, :update, :destroy]

  def index
    @q = User.ransack params[:q]
    @users = @q.result(distinct: true).paginate page: params[:page],
      per_page: Settings.subjects.users.per_page
    @q.build_sort if @q.sorts.empty?
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = t "views.messages.create_successfully"
      redirect_to admin_users_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes user_params
      flash[:success] = t "views.messages.update_successfully"
    else
      render :edit
    end
    redirect_to admin_users_path
  end

  def destroy
    if @user.destroy
      flash[:success] = t "views.messages.delete_successfully"
    else
      flash[:danger] = t "views.messages.destroy_unsuccess"
    end
    redirect_to admin_users_path
  end

  private
  def init_user
    @user = User.find params[:id]
  end

  def user_params
    params.require(:user).permit :name, :email, :password,
      :password_confirmation, :avatar, :admin
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :init_user, only: [:show, :edit, :update]
  before_action :classmate!, only: :show

  def show
    @activities = @user.activities.recent.paginate page: params[:page],
      per_page: Settings.activities.per_page
  end

  def update
    if @user.update_attributes user_params
      flash[:success] = t "views.messages.update_successfully"
    else
      render :edit
    end
    redirect_to @user
  end

  private
  def init_user
    @user = User.find params[:id]
  end

  def classmate!
    redirect_to root_path if (@user != current_user) && (!current_user.classmate? @user)
  end

  def user_params
    params.require(:user).permit :name, :password,
      :password_confirmation, :avatar
  end
end

app/views/admin/users/_form.html.erb
<%= form_for [:admin, user] do |f| %>
  <%= render "shared/error_messages", object: user %>
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :password %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, t("views.messages.confirmation") %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.file_field :avatar, id: "user_avatar" %>

  <%= f.submit t("views.messages.submit"), class: "btn btn-primary" %>
<% end %>

app/views/admin/users/_form_edit.html.erb
<%= form_for [:admin, user] do |f| %>
  <%= f.hidden_field :admin, value: true , class: "form-control" %>

  <%= f.submit t("views.actions.set_admin"), class: "btn btn-primary",
    data: {confirm: t("views.messages.confirm_admin")} %>
<% end %>

app/views/admin/users/index.html.erb
 <% provide :title, t("views.pages.users") %>

<div class="row">
  <aside class="col-md-8">
    <h1><%= t "views.pages.users" %></h1>
    <table class="table table-bordered table-hover">
      <tr>
        <th><%= t "users.id" %></th>
        <th><%= t "users.name" %></th>
        <th><%= t "users.email" %></th>
        <th><%= t "users.created" %></th>
        <th><%= t "users.updated" %></th>
        <th><%= t "views.actions.delete" %></th>
        <th><%= t "views.actions.set_admin" %></th>
      </tr>
      <% @users.each do |user| %>
        <tr data-link="<%= admin_users_path(user) %>">
          <td><%= user.id %></td>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.created_at.strftime(Settings.date_format) %></td>
          <td><%= user.updated_at.strftime(Settings.date_format) %></td>
          <td>
            <%= link_to t("views.actions.delete"), admin_user_path(user),
              method: :delete, data: {confirm: t("views.messages.confirm")},
              class: "btn btn-primary" %>
          </td>
          <td><%= render "form_edit", user: user unless user.admin? %></td>
        </tr>
      <% end %>
    </table>
    <%= will_paginate %>
  </aside>
  <aside class="col-md-4">
    <br>
    <%= link_to t("views.messeager.create_new_user"), new_admin_user_path,
      class: "btn btn-primary" %>
    <%= render "shared/search_form" %>
  </aside>
</div>

app/views/admin/users/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h2><%= t "views.messages.create_new_user" %></h2>
    <%= render "form", user: @user %>
  </div>
</div>